version: "2"

linters:
  default: none
  enable:
    - misspell
    - govet
  settings:
    misspell:
      locale: UK
      ignore-rules:
        - color
        - Color
        - COLOR
        - Organization

formatters:
  enable:
    - gofmt
