version: "2"

linters:
  default: none
  enable:
    - errcheck
    - govet
    - ineffassign
    - misspell
    - staticcheck
    - unused
  settings:
    misspell:
      locale: UK
      ignore-rules:
        - color
        - Color
        - COLOR
        - Organization
    errcheck:
      exclude-functions:
        - fmt.Fprint
        - fmt.Fprintf
        - fmt.Fprintln
        - (io.Writer).Write

formatters:
  enable:
    - gofmt
